#!/usr/bin/env bash
# build-crontab.sh — assemble the live crontab from the base + per-agent fragments.
#
# SOURCE OF TRUTH is split (both git-tracked):
#   ~/code/dotfiles/crontab.vps      base — system / vault / integration / generic jobs
#   ~/vault/agents/<name>/crontab    that agent's OWN scheduled jobs (co-located with it)
#
# This script concatenates them and installs via `crontab -`. It is now THE
# install path. Do NOT run `crontab ~/code/dotfiles/crontab.vps` directly any
# more — that would drop every agent's cron (the drift trap). Edit a source file,
# then re-run this.
#
#   build-crontab.sh            assemble + install
#   build-crontab.sh --dry-run  print what WOULD be installed; install nothing
set -euo pipefail

BASE="$HOME/code/dotfiles/crontab.vps"
AGENTS_DIR="$HOME/vault/agents"
[ -f "$BASE" ] || { echo "build-crontab: base $BASE not found" >&2; exit 1; }

assemble() {
  echo "# ============================================================"
  echo "# GENERATED by build-crontab.sh — DO NOT EDIT THE LIVE CRONTAB."
  echo "# Edit the base (~/code/dotfiles/crontab.vps) or an agent fragment"
  echo "# (~/vault/agents/<name>/crontab), then re-run build-crontab.sh."
  echo "# ============================================================"
  echo
  cat "$BASE"
  for f in "$AGENTS_DIR"/*/crontab; do
    [ -f "$f" ] || continue
    agent="$(basename "$(dirname "$f")")"
    echo
    echo "# ---- agent: $agent (~/vault/agents/$agent/crontab) ----"
    cat "$f"
    # guarantee a trailing newline so the next fragment can't merge onto the last line
    if [ -n "$(tail -c1 "$f")" ]; then echo; fi
  done
}

if [ "${1:-}" = "--dry-run" ]; then
  assemble
  exit 0
fi

TMP="$(mktemp)"
assemble > "$TMP"
crontab "$TMP"
rm -f "$TMP"
N=$(ls "$AGENTS_DIR"/*/crontab 2>/dev/null | wc -l | tr -d ' ')
echo "✓ crontab installed: base + ${N} agent fragment(s)"
